name: Java CI/CD - Build & Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy Projeto na Azure"]
    branches: [main]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Java Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build API
        run: mvn clean package -DskipTests -Dquarkus.package.type=uber-jar -Dquarkus.package.output-name=app
        working-directory: ./java

      - name: Build Email Worker
        run: mvn clean package -DskipTests -Dquarkus.package.type=uber-jar -Dquarkus.package.output-name=app
        working-directory: ./tech-challenge-envia-e-mail

      - name: Build Relatorio Worker
        run: mvn clean package -DskipTests -Dquarkus.package.type=uber-jar -Dquarkus.package.output-name=app
        working-directory: ./tech-challenge-relatorio

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: java/target/app-runner.jar

      - name: Upload Worker Artifact
        uses: actions/upload-artifact@v4
        with:
          name: worker-app
          path: tech-challenge-envia-e-mail/target/app-runner.jar

      - name: Upload Relatorio Artifact
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-app
          path: tech-challenge-relatorio/target/app-runner.jar

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download API
        uses: actions/download-artifact@v4
        with:
          name: api-app
          path: api

      - name: Download Worker
        uses: actions/download-artifact@v4
        with:
          name: worker-app
          path: worker

      - name: Download Relatorio
        uses: actions/download-artifact@v4
        with:
          name: relatorio-app
          path: relatorio

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Preparar e Zipar API
        run: |
          JAR_PATH=$(find api -name "*runner.jar" -type f | head -n 1)
          mv "$JAR_PATH" app.jar
          zip api-package.zip app.jar

      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-techchallengefeedback'
          package: 'api-package.zip'

      - name: Preparar e Zipar Worker Fila
        run: |
          JAR_PATH=$(find worker -name "*runner.jar" -type f | head -n 1)
          mv "$JAR_PATH" app.jar
          zip worker-package.zip app.jar

      - name: Deploy Worker Fila
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'worker-techchallengefeedback'
          package: 'worker-package.zip'

      - name: Preparar e Zipar Worker Relatorio
        run: |
          JAR_PATH=$(find relatorio -name "*runner.jar" -type f | head -n 1)
          mv "$JAR_PATH" app.jar
          zip relatorio-package.zip app.jar

      - name: Deploy Worker Relatorio
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'worker-reports-techchallengefeedback'
          package: 'relatorio-package.zip'