name: Infra DevOps (Plan & Apply)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Deploy Projeto na Azure'
    runs-on: ubuntu-latest

    steps:
      - name: Baixar CÃ³digo
        uses: actions/checkout@v4

      - name: Login na Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Iniciar Terraform
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        working-directory: ./infra

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./infra
        env:
          TF_LOG: DEBUG